/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as CheckerRouteImport } from './routes/checker'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicJagxConnectDotapkRouteImport } from './routes/api/public/jagx-connect[.]apk'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckerRoute = CheckerRouteImport.update({
  id: '/checker',
  path: '/checker',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicJagxConnectDotapkRoute =
  ApiPublicJagxConnectDotapkRouteImport.update({
    id: '/api/public/jagx-connect.apk',
    path: '/api/public/jagx-connect.apk',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/checker': typeof CheckerRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/public/jagx-connect.apk': typeof ApiPublicJagxConnectDotapkRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/checker': typeof CheckerRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/public/jagx-connect.apk': typeof ApiPublicJagxConnectDotapkRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/checker': typeof CheckerRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/public/jagx-connect.apk': typeof ApiPublicJagxConnectDotapkRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/checker'
    | '/sitemap.xml'
    | '/api/public/jagx-connect.apk'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/checker'
    | '/sitemap.xml'
    | '/api/public/jagx-connect.apk'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/checker'
    | '/sitemap.xml'
    | '/api/public/jagx-connect.apk'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CheckerRoute: typeof CheckerRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicJagxConnectDotapkRoute: typeof ApiPublicJagxConnectDotapkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checker': {
      id: '/checker'
      path: '/checker'
      fullPath: '/checker'
      preLoaderRoute: typeof CheckerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/jagx-connect.apk': {
      id: '/api/public/jagx-connect.apk'
      path: '/api/public/jagx-connect.apk'
      fullPath: '/api/public/jagx-connect.apk'
      preLoaderRoute: typeof ApiPublicJagxConnectDotapkRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CheckerRoute: CheckerRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicJagxConnectDotapkRoute: ApiPublicJagxConnectDotapkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
